[package]
name = "apalis-core"
version = "0.5.0-alpha.0"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Core for apalis: simple, extensible multithreaded background processing for Rust"
categories = ["concurrency"]
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = { version = "1.0", features = ["derive"] }
futures = { version = "0.3", features = ["async-await"] }
tower = { version = "0.4", features = ["util"], default-features = false }
pin-project-lite = "0.2.13"
async-oneshot = "0.5.9"
thiserror = "1.0.56"


[dependencies.document-features]
version = "0.2"
optional = true

[features]
default = []
docsrs = ["document-features"]

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
tokio = { version = "1.35.1", features = ["macros", "rt", "sync"] }
tokio-stream = "0.1.14"
# apalis-sql = { path = "../apalis-sql", features = ["tokio-comp"] }
