[package]
name = "apalis"
version = "0.5.0-alpha.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "Simple, extensible multithreaded background job processing for Rust"
repository = "https://github.com/geofmureithi/apalis"
documentation = "https://docs.rs/apalis"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["job", "task", "scheduler", "worker", "cron"]
categories = ["database"]
edition = "2021"

[lib]
bench = false

[features]
default = ["tracing", "tokio-comp"]

## Include redis storage
redis = ["apalis-redis"]
## Include Postgres storage
postgres = ["apalis-sql/postgres"]
## Include SQlite storage
sqlite = ["apalis-sql/sqlite"]
# ## Include MySql storage
mysql = ["apalis-sql/mysql"]
# ## Include Cron functionality
cron = ["apalis-cron"]

## Support Tracing 👀
tracing = ["apalis-utils/trace"]

## Support for Sentry exception and performance monitoring
sentry = ["apalis-utils/sentry"]
## Support Prometheus metrics
prometheus = ["apalis-utils/prometheus"]
## Support direct retrying jobs
retry = ["apalis-utils/retry"]
## Support timeouts on jobs
timeout = ["apalis-utils/timeout"]
## 💪 Limit the amount of jobs 
limit = ["apalis-utils/limit"]
## Support filtering jobs based on a predicate
filter = ["apalis-utils/filter"]
## Compatibility with async-std and smol runtimes
async-std-comp = [
  "apalis-sql?/async-std-comp",
  "apalis-redis?/async-std-comp",
  "apalis-cron?/async-std-comp",
]
## Compatibility with tokio and actix runtimes
tokio-comp = [
  "apalis-sql?/tokio-comp",
  "apalis-redis?/tokio-comp",
  "apalis-cron?/tokio-comp",
  "apalis-utils/tokio-comp",
]


docsrs = ["document-features"]


[dependencies.apalis-redis]
version = "0.5.0-alpha.0"
optional = true
path = "./packages/apalis-redis"
default-features = false

[dependencies.apalis-sql]
version = "0.5.0-alpha.0"
features = ["migrate"]
optional = true
default-features = false
path = "./packages/apalis-sql"

[dependencies.apalis-core]
version = "0.5.0-alpha.0"
default-features = false
path = "./packages/apalis-core"

[dependencies.apalis-cron]
version = "0.5.0-alpha.0"
optional = true
default-features = false
path = "./packages/apalis-cron"

[dependencies.apalis-utils]
version = "0.1.0"
default-features = false
path = "./packages/apalis-utils"
optional = true

[dependencies.document-features]
version = "0.2"
optional = true


[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
pprof = { version = "0.13", features = ["flamegraph"] }
paste = "1.0.14"
serde = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
apalis-redis = { version = "0.5.0-alpha.0", path = "./packages/apalis-redis" }
apalis-sql = { version = "0.5.0-alpha.0", path = "./packages/apalis-sql", features = [
  "sqlite",
  "postgres",
   "mysql"
] }

[[bench]]
name = "storages"
harness = false

[workspace]
members = [
  "packages/apalis-utils",
  "packages/apalis-core",
  "packages/apalis-redis",
  "packages/apalis-sql",
  "packages/apalis-cron",
  # Examples
  "examples/email-service",
  "examples/redis",
  "examples/actix-web",
  "examples/sqlite",
  "examples/sentry",
  "examples/mysql",
  "examples/postgres",
  "examples/axum",
  "examples/prometheus",
  "examples/tracing",
  # "examples/rest-api",
  "examples/async-std-runtime",
  "examples/basics",
]
