[package]
name = "apalis-utils"
version = "0.1.0"
edition = "2021"

[features]
default = ["tokio-comp"]
sleep = ["async-timer"]
tokio-comp = ["tokio"]

[dependencies]
async-timer = { version = "1.0.0-beta.11", optional = true, default-features = false }
apalis-core = { version = "0.5.0-alpha.0", path = "../apalis-core" }
tokio = { version = "1", features = [
    "rt",
], default-features = false, optional = true }
